# Generated by Django 5.2.1 on 2025-06-05 19:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valore_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Colori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CoppiaMisura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_misura', models.CharField(help_text="Es. 'Taglia 42', 'Lunghezza 10cm per tacco'", max_length=100)),
                ('numero_scarpa_riferimento', models.IntegerField(blank=True, help_text='Numero scarpa a cui questa misura si riferisce (se applicabile)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Misure Specifiche Componenti',
                'ordering': ['descrizione_misura'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi Componente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('partita_IVA', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CASUAL', 'Casual'), ('ELEGANTE', 'Elegante'), ('SPORTIVA', 'Sportiva'), ('SANDALO', 'Sandalo'), ('STIVALE', 'Stivale'), ('ALTRO', 'Altro')], default='CASUAL', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='modelli/foto/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelli', to='gestionale.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelli_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modelli',
                'ordering': ['nome'],
                'unique_together': {('cliente', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateTimeField(default=django.utils.timezone.now)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('CONFERMATO', 'Confermato'), ('IN_PRODUZIONE', 'In produzione'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato')], default='BOZZA', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_creati', to=settings.AUTH_USER_MODEL)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='gestionale.modello')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colore', models.ForeignKey(blank=True, help_text='Colore specifico per questo componente in questo modello', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionale.colore')),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='gestionale.modello')),
                ('nome_componente', models.ForeignKey(help_text='Tipo di componente (es. Suola, Tacco)', on_delete=django.db.models.deletion.PROTECT, to='gestionale.tipocomponente')),
            ],
            options={
                'verbose_name_plural': 'Componenti del Modello',
                'ordering': ['nome_componente__nome'],
            },
        ),
        migrations.CreateModel(
            name='MisuraComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misure_associate', to='gestionale.componente')),
                ('coppia_misura', models.ForeignKey(help_text='La misura specifica (es. Lunghezza 32cm per taglia 45)', on_delete=django.db.models.deletion.PROTECT, to='gestionale.coppiamisura')),
            ],
            options={
                'verbose_name_plural': 'Misure dei Componenti',
                'unique_together': {('componente', 'coppia_misura')},
            },
        ),
        migrations.CreateModel(
            name='DettaglioOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
                ('coppia_misura_scarpa', models.ForeignKey(help_text="Taglia della scarpa per questa riga d'ordine (es. Taglia 42)", on_delete=django.db.models.deletion.CASCADE, to='gestionale.coppiamisura')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='gestionale.ordine')),
            ],
            options={
                'verbose_name_plural': 'Dettagli Ordine (per Taglia Scarpa)',
                'ordering': ['coppia_misura_scarpa__numero_scarpa_riferimento'],
                'unique_together': {('ordine', 'coppia_misura_scarpa')},
            },
        ),
    ]
