# Generated by Django 5.2.1 on 2025-06-06 15:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valore_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Colori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Taglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Es. 38, 39, 40...', unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Taglia',
                'verbose_name_plural': 'Taglie',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi Componente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('partita_IVA', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CASUAL', 'Casual'), ('ELEGANTE', 'Elegante'), ('SPORTIVA', 'Sportiva'), ('SANDALO', 'Sandalo'), ('STIVALE', 'Stivale'), ('ALTRO', 'Altro')], default='CASUAL', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='modelli/foto/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelli', to='gestionale.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelli_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modelli',
                'ordering': ['nome'],
                'unique_together': {('cliente', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colore', models.ForeignKey(blank=True, help_text='Colore specifico per questo componente in questo modello', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionale.colore')),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='gestionale.modello')),
                ('nome_componente', models.ForeignKey(help_text='Tipo di componente (es. Suola, Tacco)', on_delete=django.db.models.deletion.PROTECT, to='gestionale.tipocomponente')),
            ],
            options={
                'verbose_name_plural': 'Componenti del Modello',
                'ordering': ['nome_componente__nome'],
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateTimeField(default=django.utils.timezone.now)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('CONFERMATO', 'Confermato'), ('IN_PRODUZIONE', 'In produzione'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato')], default='BOZZA', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_creati', to=settings.AUTH_USER_MODEL)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='gestionale.modello')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='gestionale.ordine')),
                ('taglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale.taglia')),
            ],
            options={
                'verbose_name_plural': 'Dettagli Ordine',
                'ordering': ['taglia__numero'],
                'unique_together': {('ordine', 'taglia')},
            },
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altezza', models.DecimalField(decimal_places=2, help_text='Altezza del componente in mm per questa taglia', max_digits=6)),
                ('larghezza', models.DecimalField(decimal_places=2, help_text='Larghezza del componente in mm per questa taglia', max_digits=6)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='gestionale.componente')),
                ('taglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='gestionale.taglia')),
            ],
            options={
                'verbose_name': 'Articolo (Misura Componente per Taglia)',
                'verbose_name_plural': 'Articoli (Misure Componenti per Taglia)',
                'unique_together': {('componente', 'taglia')},
            },
        ),
    ]
