# Generated by Django 5.2.1 on 2025-06-05 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='componente', max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True, default='componente di default', null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi Componente',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['nome_componente__nome'], 'verbose_name_plural': 'Componenti del Modello'},
        ),
        migrations.AlterModelOptions(
            name='coppiamisura',
            options={'ordering': ['descrizione_misura'], 'verbose_name_plural': 'Misure Specifiche Componenti'},
        ),
        migrations.AlterModelOptions(
            name='dettaglioordine',
            options={'ordering': ['coppia_misura_scarpa__numero_scarpa_riferimento'], 'verbose_name_plural': 'Dettagli Ordine (per Taglia Scarpa)'},
        ),
        migrations.AlterUniqueTogether(
            name='coppiamisura',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='componente',
            name='coppie_misure',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='nome',
        ),
        migrations.AlterUniqueTogether(
            name='dettaglioordine',
            unique_together={('ordine', 'coppia_misura_scarpa')},
        ),
        migrations.AddField(
            model_name='coppiamisura',
            name='descrizione_misura',
            field=models.CharField(default='descrizione', help_text="Es. 'Taglia 42', 'Lunghezza 10cm per tacco'", max_length=100),
        ),
        migrations.AddField(
            model_name='coppiamisura',
            name='numero_scarpa_riferimento',
            field=models.IntegerField(blank=True, help_text='Numero scarpa a cui questa misura si riferisce (se applicabile)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='dettaglioordine',
            name='coppia_misura_scarpa',
            field=models.ForeignKey(default=40, help_text="Taglia della scarpa per questa riga d'ordine (es. Taglia 42)", on_delete=django.db.models.deletion.CASCADE, to='gestionale.coppiamisura'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='colore',
            field=models.ForeignKey(blank=True, default='generico', help_text='Colore specifico per questo componente in questo modello', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionale.colore'),
        ),
        migrations.AddField(
            model_name='componente',
            name='nome_componente',
            field=models.ForeignKey(default='componente', help_text='Tipo di componente (es. Suola, Tacco)', on_delete=django.db.models.deletion.PROTECT, to='gestionale.tipocomponente'),
        ),
        migrations.RemoveField(
            model_name='coppiamisura',
            name='altezza',
        ),
        migrations.RemoveField(
            model_name='coppiamisura',
            name='larghezza',
        ),
        migrations.RemoveField(
            model_name='coppiamisura',
            name='numero_scarpa',
        ),
        migrations.RemoveField(
            model_name='dettaglioordine',
            name='coppia_misura',
        ),
        migrations.CreateModel(
            name='MisuraComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misure_associate', to='gestionale.componente')),
                ('coppia_misura', models.ForeignKey(help_text='La misura specifica (es. Lunghezza 32cm per taglia 45)', on_delete=django.db.models.deletion.PROTECT, to='gestionale.coppiamisura')),
            ],
            options={
                'verbose_name_plural': 'Misure dei Componenti',
                'unique_together': {('componente', 'coppia_misura')},
            },
        ),
    ]
