# Generated by Django 5.2.1 on 2025-07-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='altezza',
        ),
        migrations.RemoveField(
            model_name='articolo',
            name='larghezza',
        ),
        migrations.AddField(
            model_name='articolo',
            name='superficie_mq',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Superficie del componente in metri quadrati per questa taglia', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='superficie_piedi_quadri',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Superficie del componente in piedi quadrati per questa taglia', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taglia',
            name='numero',
            field=models.DecimalField(decimal_places=2, help_text='Es. 38, 39, 40...', max_digits=5, unique=True),
        ),
    ]
