# Generated by Django 5.2.1 on 2025-07-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_remove_articolo_altezza_remove_articolo_larghezza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrutturaModello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es. Décolleté Base, Stivale Texano, Sandalo Gioiello', max_length=100, unique=True)),
                ('tipi_componente', models.ManyToManyField(help_text='Seleziona i componenti base per questo tipo di struttura.', to='gestionale.tipocomponente')),
            ],
            options={
                'verbose_name': 'Struttura Modello',
                'verbose_name_plural': 'Strutture Modello',
                'ordering': ['nome'],
            },
        ),
    ]
