# Generated by Django 5.2.1 on 2025-06-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_tipocomponente_alter_componente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioordine',
            name='coppia_misura_scarpa',
            field=models.ForeignKey(default='', help_text="Taglia della scarpa per questa riga d'ordine (es. Taglia 42)", on_delete=django.db.models.deletion.CASCADE, to='gestionale.coppiamisura'),
        ),
    ]
