# Generated by Django 5.2.1 on 2025-09-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0003_strutturamodello'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='quantita_unitaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Usato se l'unità di misura è 'Pezzi', 'Paia' o 'Metri'.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='unita_misura',
            field=models.CharField(choices=[('SUPERFICIE', 'Superficie (mq/ft²)'), ('PEZZI', 'Pezzi'), ('PAIA', 'Paia'), ('METRI', 'Metri')], default='SUPERFICIE', help_text='Unità di misura per il calcolo del fabbisogno.', max_length=10),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='superficie_mq',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Usato se l'unità di misura del componente è 'Superficie'.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='superficie_piedi_quadri',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Usato se l'unità di misura del componente è 'Superficie'.", max_digits=10, null=True),
        ),
    ]
