# Generated by Django 5.2.1 on 2025-09-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0004_articolo_quantita_unitaria_componente_unita_misura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='cod_colore',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod. Colore Fornitore'),
        ),
        migrations.AddField(
            model_name='componente',
            name='cod_componente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod. Articolo/Componente'),
        ),
        migrations.AddField(
            model_name='componente',
            name='descrizione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrizione Materiale'),
        ),
    ]
