# Generated by Django 5.2.1 on 2025-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0005_componente_cod_colore_componente_cod_componente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modello',
            name='codice_articolo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Articolo (Codice)'),
        ),
        migrations.AddField(
            model_name='modello',
            name='forma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='data_consegna',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Consegna Prevista'),
        ),
    ]
